### ISSUE TITLE
How to use this method to solve small object detection

### ISSUE THREAD

**Issue by zhaobingbingbing** [IIMarch/tiny-face-mxnet#2]
如果想将本文的方法用于解决其他小目标检测（比如应用于coco,voc数据集），应该做哪些修改？
感谢回复

**Comment by KeyKy** [comment]
我感觉关键还是anchor的生成是通过聚类得到，而且和小物体的匹配方式得多考虑一下，再就是基础模型吧。。。我反正看tiny face源码的时候就这么觉得的。虽然我不一定看的对哈。。
